// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Idiom {
  final String idiom;
  final String pinyin;
  final String pinyinTone;
  final String meaning;

  const Idiom({
    required this.idiom,
    required this.pinyin,
    required this.pinyinTone,
    required this.meaning,
  });

  @override
  int get hashCode =>
      idiom.hashCode ^ pinyin.hashCode ^ pinyinTone.hashCode ^ meaning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Idiom &&
          runtimeType == other.runtimeType &&
          idiom == other.idiom &&
          pinyin == other.pinyin &&
          pinyinTone == other.pinyinTone &&
          meaning == other.meaning;
}
