// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class PracticeStatus {
  final int hit;
  final int current;
  final int practiceId;
  final int createAt;

  const PracticeStatus({
    required this.hit,
    required this.current,
    required this.practiceId,
    required this.createAt,
  });

  @override
  int get hashCode =>
      hit.hashCode ^ current.hashCode ^ practiceId.hashCode ^ createAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeStatus &&
          runtimeType == other.runtimeType &&
          hit == other.hit &&
          current == other.current &&
          practiceId == other.practiceId &&
          createAt == other.createAt;
}
