// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class BrowserHistory {
  final int visitId;
  final String url;
  final int createAt;
  final int isDeleted;

  const BrowserHistory({
    required this.visitId,
    required this.url,
    required this.createAt,
    required this.isDeleted,
  });

  @override
  int get hashCode =>
      visitId.hashCode ^ url.hashCode ^ createAt.hashCode ^ isDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BrowserHistory &&
          runtimeType == other.runtimeType &&
          visitId == other.visitId &&
          url == other.url &&
          createAt == other.createAt &&
          isDeleted == other.isDeleted;
}
