// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'vitrual_file.dart';
part 'virtual_folder.freezed.dart';

@freezed
sealed class FileOrFolder with _$FileOrFolder {
  const factory FileOrFolder.file(
    VirtualFile field0,
  ) = FileOrFolder_File;
  const factory FileOrFolder.folder(
    VirtualFolder field0,
  ) = FileOrFolder_Folder;
}

class VirtualFolder {
  final int folderId;
  final int createAt;
  final int isDeleted;
  final String folderName;

  const VirtualFolder({
    required this.folderId,
    required this.createAt,
    required this.isDeleted,
    required this.folderName,
  });

  @override
  int get hashCode =>
      folderId.hashCode ^
      createAt.hashCode ^
      isDeleted.hashCode ^
      folderName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualFolder &&
          runtimeType == other.runtimeType &&
          folderId == other.folderId &&
          createAt == other.createAt &&
          isDeleted == other.isDeleted &&
          folderName == other.folderName;
}
