// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class VirtualFile {
  final int fileId;
  final String virtualPath;
  final String realPath;
  final String fileType;
  final String icon;
  final String openWith;
  final int createAt;
  final int isDeleted;

  const VirtualFile({
    required this.fileId,
    required this.virtualPath,
    required this.realPath,
    required this.fileType,
    required this.icon,
    required this.openWith,
    required this.createAt,
    required this.isDeleted,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      virtualPath.hashCode ^
      realPath.hashCode ^
      fileType.hashCode ^
      icon.hashCode ^
      openWith.hashCode ^
      createAt.hashCode ^
      isDeleted.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VirtualFile &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          virtualPath == other.virtualPath &&
          realPath == other.realPath &&
          fileType == other.fileType &&
          icon == other.icon &&
          openWith == other.openWith &&
          createAt == other.createAt &&
          isDeleted == other.isDeleted;
}
