// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.0.0-dev.21.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../browser/history.dart';
import '../files/virtual_folder.dart';
import '../files/vitrual_file.dart';
import '../frb_generated.dart';
import '../idiom/model.dart';
import '../idiom/practice.dart';
import '../native_sysinfo.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name, dynamic hint}) =>
    RustLib.instance.api.greet(name: name, hint: hint);

Future<String> getChangelogs({dynamic hint}) =>
    RustLib.instance.api.getChangelogs(hint: hint);

Future<String> rustBridgeSayHello({dynamic hint}) =>
    RustLib.instance.api.rustBridgeSayHello(hint: hint);

Future<void> setDbPath({required String s, dynamic hint}) =>
    RustLib.instance.api.setDbPath(s: s, hint: hint);

Future<void> initDb({dynamic hint}) => RustLib.instance.api.initDb(hint: hint);

/// operation-logger
Future<void> newLog({required String content, String? result, dynamic hint}) =>
    RustLib.instance.api.newLog(content: content, result: result, hint: hint);

/// files
Future<int> newFile(
        {required String virtualPath,
        required String realPath,
        dynamic hint}) =>
    RustLib.instance.api
        .newFile(virtualPath: virtualPath, realPath: realPath, hint: hint);

Stream<NativeSysInfo> sysInfoStream({dynamic hint}) =>
    RustLib.instance.api.sysInfoStream(hint: hint);

Future<void> listenSysinfo({String? name, dynamic hint}) =>
    RustLib.instance.api.listenSysinfo(name: name, hint: hint);

Future<void> setJsonPath({required String s, dynamic hint}) =>
    RustLib.instance.api.setJsonPath(s: s, hint: hint);

Future<void> setCachePath({required String s, dynamic hint}) =>
    RustLib.instance.api.setCachePath(s: s, hint: hint);

Future<void> setIdiomPath({required String s, dynamic hint}) =>
    RustLib.instance.api.setIdiomPath(s: s, hint: hint);

Future<List<Idiom>> getIdioms({int? count, dynamic hint}) =>
    RustLib.instance.api.getIdioms(count: count, hint: hint);

Future<Idiom?> getOneIdiom({required int index, dynamic hint}) =>
    RustLib.instance.api.getOneIdiom(index: index, hint: hint);

Future<void> initFolder({required String s, dynamic hint}) =>
    RustLib.instance.api.initFolder(s: s, hint: hint);

Future<void> createNewTxt(
        {required String filename,
        required String openWith,
        int? folderId,
        dynamic hint}) =>
    RustLib.instance.api.createNewTxt(
        filename: filename, openWith: openWith, folderId: folderId, hint: hint);

Future<void> deleteFile({required int id, dynamic hint}) =>
    RustLib.instance.api.deleteFile(id: id, hint: hint);

Future<void> restoreFile({required int id, dynamic hint}) =>
    RustLib.instance.api.restoreFile(id: id, hint: hint);

Future<List<FileOrFolder>> getChildrenById({int? i, dynamic hint}) =>
    RustLib.instance.api.getChildrenById(i: i, hint: hint);

Future<int> newPractice({dynamic hint}) =>
    RustLib.instance.api.newPractice(hint: hint);

Future<void> updatePractice(
        {required int hit,
        required int index,
        required int rowId,
        dynamic hint}) =>
    RustLib.instance.api
        .updatePractice(hit: hit, index: index, rowId: rowId, hint: hint);

Future<PracticeStatus?> getLastPractice({dynamic hint}) =>
    RustLib.instance.api.getLastPractice(hint: hint);

Future<void> delete3DaysAgoHistory({dynamic hint}) =>
    RustLib.instance.api.delete3DaysAgoHistory(hint: hint);

Future<void> newBrowserHistory({required String s, dynamic hint}) =>
    RustLib.instance.api.newBrowserHistory(s: s, hint: hint);

Future<List<BrowserHistory>> fetchHistory({required int page, dynamic hint}) =>
    RustLib.instance.api.fetchHistory(page: page, hint: hint);
